progetto-oop-22-23/OOP22-HOMER

app/src/main/java/homer/App.java, app/src/test/java/homer/AppTest.java
=> Solve default project style errors

app/src/main/java/homer/api/AdjustableDevice.java, app/src/main/java/homer/api/Controller.java, app/src/main/java/homer/api/Device.java, app/src/main/java/homer/api/DeviceInfo.java, app/src/main/java/homer/api/DeviceView.java, app/src/main/java/homer/api/ToggleableDevice.java
This pr will add the base interfaces to begin the project.
=> Add base interfaces

app/src/main/java/homer/DeviceInfoImpl.java
it will probably save from writing boilerplate in the future.
=> [common] add DeviceInfoImpl

app/build.gradle.kts
=> [deps] update plugin org.danilopianini.gradle-java-qa to v0.44.0

app/src/main/java/homer/common/KelvinTemperature.java, app/src/main/java/homer/common/Temperature.java, app/src/main/java/homer/common/TemperatureFactory.java, app/src/main/java/homer/common/TemperatureFactoryImpl.java, app/src/test/java/homer/common/TemperatureTest.java
@smagnaniuni  i know it lacks unit tests, but i will add them later.
=> [common] add temperature

app/src/main/java/homer/DeviceInfoImpl.java, app/src/main/java/homer/api/Controller.java, app/src/main/java/homer/api/DeviceId.java, app/src/main/java/homer/api/DeviceIdImpl.java, app/src/main/java/homer/api/DeviceInfo.java
Issue #27 
@michelececcacci DeviceInfoImpl has to be modified too should I do it?
=> Implement DeviceId

app/src/main/java/homer/model/environment/Environment.java, app/src/main/java/homer/model/environment/EnvironmentObject.java, app/src/main/java/homer/model/environment/HomeEnvironment.java
Closes #19 
@michelececcacci I am thinking of implementing another interface for a device whose location in the environment matters.
```java
public interface EnvironmentObject {
void move(Environment environment);
}
```
We would also need to specify in the constructor the environment? So the device knows where it is and can call the environment methods.
Maybe also the environment needs to keep a reference of the devices in it? But that would probably lead to problems.
=> Implement Home Environment

app/src/main/java/homer/api/DeviceId.java, app/src/main/java/homer/api/DeviceIdImpl.java, app/src/main/java/homer/common/time/Clock.java
Solves checkstyle javadoc errors and updates incomplete comments.
=> Fix javadoc

app/src/main/java/homer/common/KelvinTemperature.java, app/src/main/java/homer/common/Temperature.java, app/src/main/java/homer/common/TemperatureFactoryImpl.java, app/src/test/java/homer/common/TemperatureTest.java
=> Fix Temperature

app/src/main/java/homer/model/lights/Light.java
This PR implements a basic Light device.
I'm thinking about creating an Adjustable version, too, but for now I'd stick with Toggleable.
=> [LIGHTS] Implement basic light

app/src/main/java/homer/api/DeviceIdImpl.java
@michelececcacci there is also a pmd error in TemperatureTest `JUnit 5 tests should be package-private.`
I didn't fix it since I know you are working around there
=> [pmd] fix missing override

app/src/main/java/homer/model/environment/EnvironmentObject.java
Do we need a getEnvironment method? Not view-side.
Otherwise I will proceed to remove it completely, and we can revert in the future if we need it.
=> [environment] remove EnvironmentObject

build.gradle.kts, src/main/java/homer/model/temperaturechangers/AbstractTemperatureChanger.java, src/main/java/homer/model/temperaturechangers/AirConditioning.java, src/main/java/homer/model/temperaturechangers/Heating.java, src/main/java/homer/model/temperaturechangers/TemperatureChanger.java, src/test/java/homer/model/temperaturechangers/AirConditioningTest.java, src/test/java/homer/model/temperaturechangers/HeatingTest.java
still some PMD errors, i will fix them later. should be fine both conceptually and test wise
=> Temperaturechangers

src/main/java/homer/model/outlets/Outlet.java, src/main/java/homer/model/outlets/OutletFactory.java, src/test/java/homer/model/outlets/OutletTest.java
Bug fix and now CI should pass.
=> Feature/outlets passing CI

src/main/java/homer/common/time/DurationConverter.java, src/test/java/homer/common/time/TestDurationConverter.java
@smagnaniuni should be fine, i'll add more tests if you like it
=> [common] introduce DurationConverter

src/main/java/homer/common/bounds/Bounds.java
Would allow to create range boundaries for other comparable types such as time and temperature.
=> [bounds] remove extends Number requirement on the Bounds generic type

src/main/java/homer/controller/Controller.java, src/main/java/homer/controller/ViewManagerImpl.java, src/main/java/homer/view/JFXApplication.java, src/main/java/homer/view/View.java, src/main/java/homer/view/javafx/DeviceViewImpl.java, src/main/java/homer/view/javafx/DisconnectDeviceButton.java, src/main/java/homer/view/javafx/SliderComponent.java
Also added a disconnect button in DeviceViewImpl.
=> General updates to View

src/main/java/homer/view/JFXApplication.java, src/main/java/homer/view/sim/SimManagerViewFxImpl.java
Adds BorderPane
Adds TabPane for the different views.
Converts SimManagerView FX implementation to a HBox and sets it at the bottom
=> Major view refactor

src/main/java/homer/controller/ControllerImpl.java, src/main/java/homer/controller/DeviceManager.java, src/main/java/homer/controller/DeviceManagerImpl.java, src/main/java/homer/controller/DeviceManagerObserver.java, src/main/java/homer/controller/command/ToggleDevice.java, src/main/java/homer/controller/command/UpdateDeviceState.java
Also the methods `toggleDevice` and `removeAllDevices` might be a bit redundant but fine to keep.
=> [controller] refactor DeviceManager by separating logic and view methods

src/main/java/homer/controller/ControllerImpl.java
Use the iterator to remove the element.
=> [controller] fix commands execution

src/main/java/homer/view/JFXApplication.java, src/main/java/homer/view/javafx/JFXDeviceViewer.java
The create commands need to be updated too, currently they set min and max to 0.
=> Make dashboard work

src/main/java/homer/controller/ControllerImpl.java, src/main/java/homer/controller/scheduler/TemperatureSchedulerController.java, src/main/java/homer/controller/scheduler/TimeSchedulerController.java, src/main/java/homer/core/SimManager.java, src/main/java/homer/core/SimManagerImpl.java, src/main/java/homer/core/SimManagerViewObserver.java, src/main/java/homer/view/JFXApplication.java
Add the possibility for the sim loop to update additional DiscreteObject observers.
Refactor scheduler controller as a DiscreteObject
=> Sim and scheduler refactors

src/main/java/homer/view/sim/SimManagerViewFxImpl.java
Changed rate and datetime format.
=> sim view qol improvements

src/main/java/homer/view/javafx/JFXDeviceViewer.java, src/main/java/homer/view/javafx/SliderComponent.java, src/main/java/homer/view/javafx/deviceview/ActuatedDeviceView.java, src/main/java/homer/view/javafx/deviceview/ReadOnlyActuatedDeviceView.java, src/main/java/homer/view/javafx/deviceview/TemperatureChangerView.java, src/main/java/homer/view/javafx/deviceview/ThermometerView.java, src/main/java/homer/view/javafx/deviceview/ToggleableView.java
@smagnaniuni should be good, pinging just in case.
=> fix actuatedDevice views

src/main/java/homer/api/state/LockState.java, src/main/java/homer/model/lock/SimpleLock.java, src/main/java/homer/view/javafx/deviceview/LockView.java, src/main/java/homer/view/logger/LoggerImpl.java, src/test/java/homer/model/lock/SimpleLockTest.java
=> rename LockState isOn to isLocked
